Repository storyblok/storyblok-design-system, pull requests merged in 2022-07, with the labels that each got.

#241 bugfix(work-393): update `deselectRow` function to remove the correct row
  src/components/DataTable/index.js
Labels: easy to review

#239 task(int-452): Remove icon right in sbMenuButton and add color in icon the button
  src/components/Button/Button.stories.js
  src/components/Button/index.js
  src/components/Menu/Menu.stories.js
  src/components/Menu/index.js
  src/components/Menu/menu.scss
Labels: easy to review

#242 bugfix(INT-439): slideover title overlap icon
  src/components/Slideover/slideover.scss
Labels: easy to review

#235 refactor(tabs): padding update
  src/components/Tabs/tabs.scss
Labels: needs rework

#260 bugfix(STR-1137): SbDropArea: Problems with drag and drop
  src/components/DropArea/drop-area.scss
Labels: good first issue
