Repository storyblok/storyblok-design-system, pull requests merged in 2023-11, with the labels that each got.

#470 :bug: fix(ON-1500): adds Esc key listener when is-open is true on created hook
  src/components/Modal/SbModal.vue
Labels: bug, easy to review

#460 task (INT-1066): Datetime 24/12 feature + Styles updates
  src/components/Datepicker/Datepicker.stories.js
  src/components/Datepicker/Datepicker.vue
  src/components/Datepicker/__tests__/DatepickerTime.spec.js
  src/components/Datepicker/components/DatepickerTime.vue
  src/components/Datepicker/datepicker.scss
  src/components/Datepicker/utils.ts
  src/utils/index.js
  src/utils/timezones.ts
Labels: waiting for QA

#474 feat(STR-2000): fix rounded corner on the upload progress bar
  .storybook/preview.css
  src/components/UploadDialog/UploadDialog.stories.js
  src/components/UploadDialog/UploadDialog.vue
  src/components/UploadDialog/upload-dialog.scss
Labels: in QA Testing

#477 refactor(work-1263): adding data-testid to the MenuGroup component
  src/components/Menu/MenuGroup.vue
Labels: easy to review
